### ISSUE TITLE
A question about the package

### ISSUE THREAD

**Issue by OrdinarySK** [samuel-rosa/spsann#17]
Excuse me, "**spsann**" package could calculation multi-object **MKV** based weight.

**Comment by samuel-rosa** [comment]
@OrdinarySK I am not sure if I understand your question. Could you please elaborate on it?

**Comment by OrdinarySK** [comment]
Of course, I need to solve Multi-objective site optimization problem. The objective function is the weighting of multiple MKVs or pareto, based on LMC(linear model of coregionalization). function **optimMKV** could calculated optimized site. If the function cannot be optimized, you can give me some suggestions? Thank you.

**Comment by samuel-rosa** [comment]
@OrdinarySK __spsann__ does not have a built-in function to optimize sample configurations based on the linear model of coregionalization. The `optimMKV` optimizes sample configurations with respect to the autovariogram of a single regionalized variable.

You could implement your own objective function and optimize the sample configuration using `optimUSER`. Alexandre Wadoux has done it in a recent paper (DOI:10.1016/j.advwatres.2017.06.005)
