### ISSUE TITLE
Some theoretical issues of SPSANN

### ISSUE THREAD

**Issue by yancong723** [samuel-rosa/spsann#20]
1、
The **obj**=1/3**CORR**+1/3**DIST**+1/3**MSSD**  in my opinion. However the  **obj**=**CORR+DIST+PPL+MSSD** in this picture. Where reflects the **weights** ?
![image](https://user-images.githubusercontent.com/50294885/93692119-ad682e80-fb21-11ea-84a6-095eb1f179ca.png)
2、
For the multi-objective combinatorial optimization problem,we use **the upper-lower-bound approach** to scale the
objective functions.Each objective function is between 0 and 1. Why the obj is so large such as obj =20 ?
![image](https://user-images.githubusercontent.com/50294885/93692130-cbce2a00-fb21-11ea-95ec-a96a6eca8074.png)
3、
How to mark points for current sample configuration? So that we can intuitively see which points are deleted .
Thanks!

**Comment by samuel-rosa** [comment]
Please submit a reproducible example e.g. https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by yancong723** [comment]
What I want to know is theoretical knowledge in these pictures and I may not be able to submit a reproducible example.
However I think this pictures are enough to illustrate the problem. Thanks.

**Comment by samuel-rosa** [comment]
I do not know how you set the nadir and utopia values. So, I cannot help you with this.

**Comment by yancong723** [comment]
```R
library(rgdal)
library(spsann)
paper<-read.table("clipboard",header = T)
head(paper)
candi<-paper[,1:2]
#candi<-paper[3:7,1:2]
covars<-paper[ ,3:9]
boundary<-readOGR("g:/R/paper/qian_shui_bian_jie.shp")
nadir <- list(sim = 10, seeds = 1:10)
# Step 2. Set control parameters
utopia <- list(user = list(DIST = 0, CORR = 00, PPL = 0, MSSD = 0))
schedule <- scheduleSPSANN(
  chains = 300, initial.temperature = 5, x.max = 1540, y.max = 2060, 
  x.min = 0, y.min = 0, cellsize = 10,temperature.decrease = 0.99)

weights <- list(CORR = 1/3, DIST = 1/3, PPL = 0,MSSD=1/3)
set.seed(2001)
#Step 3. Execute the simulated annealing algorithm
res <- optimSPAN(
  points = 1:31, candi = candi, covars = covars, nadir = nadir, plotit = T,use.coords = T, 
  utopia = utopia, schedule = schedule, boundary = boundary,
    weights = weights)
```

What is the effect of these two parameters ?
Thank you all the time for your reply and I learned a lot!

**Comment by samuel-rosa** [comment]
Given your results, the utopia and nadir values are too low. I recomend that you set them by optimizing each objective function individualy and then use the `minmaxPareto()` function.

**Comment by yancong723** [comment]
OK, I will take your advice for the next step.

**Comment by yancong723** [comment]
This is your case code :
```
require(sp)
data(meuse.grid)
candi <- meuse.grid[, 1:2]
covars <- meuse.grid[, c(1, 2)]
# CORR
schedule <- scheduleSPSANN(initial.acceptance = 0.1, chains = 1,
                           x.max = 1540, y.max = 2060, x.min = 0,
                           y.min = 0, cellsize = 40)
set.seed(2001)
osc_corr <- optimCORR(points = 10, candi = candi, covars = covars,
                      schedule = schedule,plotit = T)
# DIST
set.seed(2001)
osc_dist <- optimDIST(points = 10, candi = candi, covars = covars,
                      schedule = schedule,plotit = T)
# PPL
set.seed(2001)
osc_ppl <- optimPPL(points = 10, candi = candi, schedule = schedule)
# MSSD
set.seed(2001)
osc_mssd <- optimMSSD(points = 10, candi = candi, schedule = schedule)
# Pareto
pareto <- minmaxPareto(osc = list(DIST = osc_dist, CORR = osc_corr,
                                  PPL = osc_ppl, MSSD = osc_mssd),
                       candi = candi, covars = covars)
pareto
```
The output is as follows ：

```
            CORR     DIST PPL     MSSD
CORR 0.001784325 1.476313  33 164910.4
DIST 0.198182118 1.024557  34 275369.2
PPL  0.094418449 1.601096  37 191347.7
MSSD 0.293853408 1.016500  44 206622.7
```

I want to draw the following figure -2D or 3D Pareto curve.How can I achieve it ?
![image](https://user-images.githubusercontent.com/50294885/96327457-627fff00-106c-11eb-8c4c-15b5e86bb91b.png)

**Comment by samuel-rosa** [comment]
The output above is to be used to set the utopia and nadir values in the multi-objective optimization. In the diagonal you have the utopia values.

**Comment by yancong723** [comment]
Given your previous advice, Is my assignment the following :
1. Optimizing each objective function individualy;
2. Setting **nadir and utopia value** by using the @minmaxPareto() function.
3. Calculating of final results  by using the optimSPSANN function 

In addition,I want to know that if each optimization function can output the function value of the iterative process or find the optimal solution set for each single objective function ?
Thanks！

**Comment by samuel-rosa** [comment]
@yancong723 you are correct -- except for the function name, which is `optimSPAN`. And yes, it will return all function values. You only need to configure it to do so -- see the function documentation.

**Comment by yancong723** [comment]
My goal is to get all the objective function values during the iteration --thousands of **obj** values.
Does the function documentation. refer to **spsann**? 
![image](https://user-images.githubusercontent.com/50294885/96731393-c9dddc00-13e9-11eb-9042-d79410dd9eef.png)
I can only find the objective function above .

**Comment by samuel-rosa** [comment]
Yes, I think that I understand your goal. To achieve this, you need to use the `optimSPAN()` function that you were using before (see previous messages).

**Comment by yancong723** [comment]
I met new problems in my attempt ：

```R
library(spsann)
paper<-read.table("clipboard",header = T)
head(paper)
candi<-paper[,2:3]
#candi<-paper[3:7,1:2]
covars<-paper[ ,4:11]
boundary<-readOGR("g:/R/paper/qian_shui_bian_jie.shp")
# Step 2. Set control parameters
schedule <- scheduleSPSANN(
  chains = 500, initial.temperature = 3,temperature.decrease = 0.95)
set.seed(121)
osc_corr<-optimCORR(points = 1:31,candi = candi,covars = covars,strata.type = "area",
                    plotit = T,schedule = schedule, boundary = boundary)
osc_dist<-optimDIST(points = 1:31,candi = candi,covars = covars,plotit = T,
                    schedule = schedule, boundary = boundary)
osc_mssd<-optimMSSD(points = 1:31,candi = candi,plotit = T,
                    schedule = schedule, boundary = boundary)
```
![image](https://user-images.githubusercontent.com/50294885/97820759-9b65d800-1cea-11eb-9797-fec964735ce0.png)
![image](https://user-images.githubusercontent.com/50294885/97820792-c05a4b00-1cea-11eb-989f-2483dd5bc1e7.png)
![image](https://user-images.githubusercontent.com/50294885/97820805-ccdea380-1cea-11eb-80bc-5dbed218ce9e.png)
The result is only a few iterations .Is this due to my data ?

**Comment by samuel-rosa** [comment]
I can't tell you if this is due to your data because I do not have access to it.

TIP: check https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks to see how to use the markdown syntax to present R code.

**Comment by yancong723** [comment]
Ok.
![image](https://user-images.githubusercontent.com/50294885/98905121-d68bb680-24f5-11eb-9987-1340626e04aa.png)
The  result is the  example of _minmaxPareto_.I found that their orders of magnitude vary greatly  did not adopt the upper-lower-bound approach.Moreover,although I've read the literature and source code,I can't understand how each value is calculated about minmaxPareto and optimDIST.Can you provide their formulas such as 
![image](https://user-images.githubusercontent.com/50294885/98905917-3171dd80-24f7-11eb-8aa3-6bda3da210d9.png).
 I am a novice and I appreciate your help greatly!

**Comment by yancong723** [comment]
Of pareto results, how should I set nadir and utopia values ?

**Comment by samuel-rosa** [comment]
The utopia and nadir values of each objective function are in the columns of your table. The utopia values (min values) are those in the diagonal. The nadir values are the largest values (max values) in each column.

**Comment by yancong723** [comment]
I already know how to set them up.In addition, could you explain DIST function again such as a series of formulas ?
https://user-images.githubusercontent.com/50294885/98905917-3171dd80-24f7-11eb-8aa3-6bda3da210d9.png

**Comment by samuel-rosa** [comment]
Please take a look at https://tede.ufrrj.br/jspui/handle/jspui/1333

**Comment by yancong723** [comment]
Existing objective functions are considered  spatial accuracy.  But many data are often monitored by time series . t is more reasonable to consider time and space at the same time . Is there an objective function for reducing time redundancy ?

**Comment by samuel-rosa** [comment]
The current version of __spsann__ works only in the geographic space. You can implement a custom time-space solution using `optimUSER`.

**Comment by yancong723** [comment]
At present, at my personal level, I can not carry out a further step of programming work. But I know that using time and space approach is cutting-edge and useful .Now I plan to combine MKV and MSSD functions, could you give me more specific comments? Such as a example.

**Comment by samuel-rosa** [comment]
@yancong723 I would love to, but my time is very limited.

**Comment by yancong723** [comment]
I plan to combine MKV and MSSD functions, could you give me more specific comments? Such as a example.

**Comment by samuel-rosa** [comment]
As I said above, I do not have the time for that now.

**Comment by yancong723** [comment]
I'm sorry to bother you again. I'd like to ask some new questions .
As needed, how to maximize a covariates while using MSSD functions to optimize .This may require me to define  the objective function. I hope to receive your substantial help as I can not understand optimUSER function.Thank you very much for your help ! 
Looking forward to your reply.

**Comment by samuel-rosa** [comment]
`optimUSER` was designed for single-objective optimization, but could be tuned to deal with two or more objectives. Unfortunately, I do not have the time needed to do this at this moment.

An alternative solution is to use `optimACDC` with `use.coords = TRUE`. The result is not the same as that of using `optimMSSD`, but should provide a good coverage of the geographic space.
